name: Go
on:
  push:
    - 'go-requests/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - uses: chrislennon/action-aws-cli@v1.1
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      working-directory: go-requests
      run: go build -v requests.go

    - name: Upload executable to s3
      working-directory: go-requests
      run: |
        zip -q go-requests.zip requests
        aws s3 cp go-requests.zip s3://bdr-go-blog

    - name: Update lambda function
      working-directory: go-requests
      run: aws lambda update-function-code --function-name api-calls-go --s3-bucket bdr-go-blog --s3-key go-requests.zip > /tmp/dumpgo