name: Python package

on:
  push:
    paths:
      - 'python-requests/**'
      - '.github/workflows/pythonpackage.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set trigger for layer creation
        run: |
          BUILD_LAYER=$(git diff)
          echo "::set-env name=BUILD_LAYER::${BUILD_LAYER}"

      - name: print
        run: |
          echo ${BUILD_LAYER}
          echo ${{ env.BUILD_LAYER }}
      - uses: chrislennon/action-aws-cli@v1.1
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Build new lambda layer
        working-directory: python-requests
        if: contains(env.BUILD_LAYER, 'python-requests/requirements.txt')
        run: |
          pip install -r requirements.txt -t python/lib/python3.7/site-packages/
          zip -rq9 python-requests-layer.zip python

      - name: Upload layer zip to S3
        working-directory: python-requests
        if: contains(env.BUILD_LAYER, 'python-requests/requirements.txt')
        run: |
          aws s3 cp python-requests-layer.zip s3://bdr-go-blog/python-requests-layer.zip

      - name: Update lambda layer using S3
        working-directory: python-requests
        if: contains(env.BUILD_LAYER, 'python-requests/requirements.txt')
        run: |
          LAYER_VERSION_ARN=$(aws lambda publish-layer-version \
          --layer-name python-requests-layer \
          --content S3Bucket=bdr-go-blog,S3Key=python-requests-layer.zip \
          --compatible-runtimes python3.7 | jq -r ".LayerVersionArn")
          echo "::set-env name=LAYER_VERSION_ARN::${LAYER_VERSION_ARN}"

      - name: Upload lambda zip to S3
        working-directory: python-requests
        run: |
          echo ${BUILD_LAYER}
          mkdir lambda-packaged
          mv api_calls_utils lambda-packaged
          cp *.py lambda-packaged/
          cd lambda-packaged && zip -rq python-requests.zip *
          aws s3 cp python-requests.zip s3://bdr-go-blog

      - name: Update lambda function
        working-directory: python-requests
        run: |
          aws lambda update-function-code --function-name \
          api-calls-python --s3-bucket bdr-go-blog --s3-key \
          python-requests.zip > /tmp/dump2

      - name: Update lambda function configuration
        working-directory: python-requests
        if: contains(env.BUILD_LAYER, 'python-requests/requirements.txt')
        run: |
          echo ${LAYER_VERSION_ARN}
          aws lambda update-function-configuration \
          --function-name api-calls-python \
          --layers ${LAYER_VERSION_ARN} > /tmp/dump
